- hosts: all
  become: yes
  tasks:
    - name: apply deployment
      command: kubectl apply -f /home/ec2-user/project/Deployment.yml

    - name: create new service
      command: kubectl apply -f /home/ec2-user/project/Service.yml
