kind: Deployment
apiVersion: apps/v1
metadata:
   name: deployment2
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: label1
   template:
      metadata:
        labels:
          app: label1
      spec:
       containers:
        - name: container1
          image: dockerpavank/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
